import os
import shutil
import platform as os_platform

num_jobs = ARGUMENTS.get('jobs', 4)
platform = ARGUMENTS.get('platform', 'windows')
target = ARGUMENTS.get('target', 'template_debug')

dest_dir = '../../src/bin/wallpaper_engine/'

env = SConscript('../godot_cpp/SConstruct')
env.Append(CPPPATH=['src'])

env.Append(LIBS=['avcodec.lib', 'avformat.lib', 'avfilter.lib', 'avdevice.lib', 'avutil.lib', 'swscale.lib', 'swresample.lib'])

#ffmpeg_bin = os.path.join(os.path.dirname('__file__'), 'ffmpeg', 'bin')
env.Append(CPPPATH=['ffmpeg/bin/include'])
env.Append(LIBPATH=['ffmpeg/bin/bin'])

if platform == "windows":
    env.Append(LIBS=["User32"])

src = Glob('src/*.cpp')
libpath = '{}libwallpapereng.{}{}'.format(dest_dir, env['suffix'], env['SHLIBSUFFIX'])
sharedlib = env.SharedLibrary(libpath, src)
Default(sharedlib)
